language: go
dist: bionic
notifications:
  email:
    recipients:
      - middleware@hexonet.net
    on_success: never
    on_failure: always
addons:
  apt:
    update: true
go:
  - "1.12"
  - "1.13"
before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.8
  - export PATH="$GOPATH/bin:$PATH"
script:
  - ./scripts/validate-go.sh
  - ./scripts/test-go.sh
jobs:
  include:
    - stage: release
      node_js: lts/*
      install:
        - rm -rf ~/.nvm
        - git clone https://github.com/creationix/nvm.git ~/.nvm
        - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
        - source ~/.nvm/nvm.sh
        - nvm install lts/*
      script:
        - npm prune
        - travis_retry npm i
        - npx semantic-release
